

/*
 * callbacks.cpp -- part of the WorkshopBot2 project.
 * Implementation of callbacks -- YOUR code goes here!
 * Nitin Vinayak Agrawal
 * Robocon 
 * 
 * Copyright (C) 2017 Nitin Vinayak Agrawal
 * 
 * Generated by DruidBuilder [https://devicedruid.com/], 
 * as part of project "abe4840fc0814befa2c60aa04c9423e0IzQOUGjFRo",
 * aka WorkshopBot2.
 * 
 * Druid4Arduino, Device Druid, Druid Builder, the builder 
 * code brewery and its wizards, SerialUI and supporting 
 * libraries, as well as the generated parts of this program 
 * are 
 *            Copyright (C) 2013-2017 Pat Deegan 
 * [http://psychogenic.com/ | http://flyingcarsandstuff.com/]
 * and distributed under the terms of their respective licenses.
 * See http://devicedruid.com for details.
 * 
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE 
 * PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, 
 * YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR
 * CORRECTION.
 * 
 * Keep in mind that there is no warranty and you are solely 
 * responsible for the use of all these cool tools.
 * 
 * Play safe, have fun.
 * 
 */


/* we need the SerialUI lib */
#include <SerialUI.h>
#include "WorkshopBot2Settings.h"

/* our project specific types and functions are here */
#include "WorkshopBot2.h"



/* 
 * In addition to any custom globals you declared,
 * here you have access to:
 * 
 * *** MySUI -- the SerialUI instance.
 * Use it as you would the Serial device, e.g.
 * 	MySUI.println(F("Helloooo..."));
 * 	
 * 	
 * *** MyInputs -- a container for 
 * values submitted by users. Contents:
 *  
 *    MyInputs.Forward (long int)
 *    MyInputs.Turn (long int)
 *    MyInputs.ServoDir (long int)
 *  
 *  
 *  
 * 
 */






/* ********* callbacks and validation functions ********* */



/* *** Main Menu *** */
namespace MainMenu {


void ForwardChanged() {

    /* forward value was modified.
    * It is a long int accessible in MyInputs.Forward
    */
    MySUI.print(F("forward is now:"));
    MySUI.println(MyInputs.Forward);

}

void TurnChanged() {

    /* turn value was modified.
    * It is a long int accessible in MyInputs.Turn
    */
    MySUI.print(F("turn is now:"));
    MySUI.println(MyInputs.Turn);

}

void ServoDirChanged() {

    /* ServoDir value was modified.
    * It is a long int accessible in MyInputs.ServoDir
    */
    MySUI.print(F("ServoDir is now:"));
    MySUI.println(MyInputs.ServoDir);

}





} /* namespace MainMenu */





