
#ifndef _WorkshopBot2_WorkshopBot2_h
#define _WorkshopBot2_WorkshopBot2_h


/*
 * WorkshopBot2.h -- part of the WorkshopBot2 project.
 * Declarations for everything that was generated...
 * Nitin Vinayak Agrawal
 * Robocon 
 * 
 * Copyright (C) 2017 Nitin Vinayak Agrawal
 * 
 * Generated by DruidBuilder [https://devicedruid.com/], 
 * as part of project "abe4840fc0814befa2c60aa04c9423e0IzQOUGjFRo",
 * aka WorkshopBot2.
 * 
 * Druid4Arduino, Device Druid, Druid Builder, the builder 
 * code brewery and its wizards, SerialUI and supporting 
 * libraries, as well as the generated parts of this program 
 * are 
 *            Copyright (C) 2013-2017 Pat Deegan 
 * [http://psychogenic.com/ | http://flyingcarsandstuff.com/]
 * and distributed under the terms of their respective licenses.
 * See http://devicedruid.com for details.
 * 
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE 
 * PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, 
 * YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR
 * CORRECTION.
 * 
 * Keep in mind that there is no warranty and you are solely 
 * responsible for the use of all these cool tools.
 * 
 * Play safe, have fun.
 * 
 */



/* we need the SerialUI lib */
#include <SerialUI.h>


/* MySUI
 * Our SerialUI Instance, through which we can send/receive
 * data from users.
 */ 
extern SUI::SerialUI MySUI;






/*
 * The container for MyInputs, which
 * holds all the variables for the various inputs.
 */
typedef struct MyInputsContainerStruct {
	
	long int Forward;
	long int Turn;
	long int ServoDir;
	// constructor to set sane startup vals
	MyInputsContainerStruct() : 
		Forward(0),
		Turn(0),
		ServoDir(0)
	{}
} MyInputsContainerSt;

extern MyInputsContainerSt MyInputs;





/* ********* callbacks and validation functions ********* */



/* *** Main Menu *** */
namespace MainMenu {

void ForwardChanged();

void TurnChanged();

void ServoDirChanged();

} /* namespace MainMenu */



/* ***** SetupSerialUI: where we'll be setting up menus and such **** */
bool SetupSerialUI();


#define DIE_HORRIBLY(msg)	for(;;){ MySUI.println(msg); delay(1000); }


#endif
